server:
 service:
   type: LoadBalancer
   annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: nlb
     service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

configs:
  cm:
    timeout.reconciliation: 60s
    resource.exclusions: |
      - apiGroups:
        - "*"
        kinds:
        - ApplyReplacements
        - WorkloadCluster
        clusters:
        - "*"
    resource.customizations.health.tf.galleybytes.com_Terraform: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.phase ~= nil then
          if obj.status.phase == "initializing" or obj.status.phase == "running" or obj.status.phase == "initializing-delete" or obj.status.phase == "deleting" then
            if obj.status.stage.state == "failed" then
              hs.status = "Degraded"
            else
              hs.status = "Progressing"
            end
          elseif obj.status.phase == "completed" then
            hs.status = "Healthy"
          else
            hs.status = "Degraded"
          end
        end
        if obj.status.stage ~= nil then
          if obj.status.stage.message ~= nil then
            hs.message = obj.status.stage.message
          end
        end
      end
      return hs
